import type { Metadata } from "next";

import { LayoutDefault } from "./ui/layouts/layout-default";

import "./ui/styles/main.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <LayoutDefault>{children}</LayoutDefault>;
}
